frameworkVersion: "2"

org: ismaelnascimentoash
app: websocket-template
service: ismaelash-template-nodejs

provider:
    name: aws
    runtime: nodejs14.x
    region: us-east-1
    stage: develop
    websocketsApiName: ${self:custom.projectName}
    websocketsApiRouteSelectionExpression: $request.body.route
    logs:
        websocket:
            level: INFO
            # role: arn:aws:iam::{AccountId}:role/serverlessAPIGatewayCloudWatchLogs
    iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:*
              - cloudwatch:*
          Resource: "*"

package:
    individually: true

custom:
    projectName: template-nodejs-websocket

functions:
    connectionHandler:
        handler: lambdas/websocketHandler.handler
        events:
            - websocket:
                  route: $connect
    disconnectHandler-:
        handler: lambdas/websocketHandler.handler
        events:
            - websocket:
                  route: $disconnect
    defaultHandler:
        handler: lambdas/websocketHandler.handler
        events:
            - websocket:
                  route: $default
    publishMessageHandler:
        handler: lambdas/websocketHandler.handler
        events:
            - websocket:
                  route: publish
    setTopicHandler:
        handler: lambdas/websocketHandler.handler
        events:
            - websocket:
                  route: setTopic

resources:
    Resources:
        TemplateNodejsWebsocket:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: template-nodejs-websocket-clientConnected
                AttributeDefinitions:
                    - AttributeName: Id
                      AttributeType: S
                KeySchema:
                    - AttributeName: Id
                      KeyType: HASH
                BillingMode: PAY_PER_REQUEST
